
icons:
	[ -e mapiconscollection-markers.zip ] || curl -O http://mapicons.nicolasmollet.com/wp-content/uploads/zip/mapiconscollection-markers.zip
	unzip mapiconscollection-markers.zip -d mapiconscollection-markers
